### ISSUE TITLE
Cannot run project with ts-node

### ISSUE THREAD

**Issue by JerryHue** [DukeManh/OSD_SSG#1]
As the issue states, I cannot test the project with `ts-node`.

I tried to run the sample code found in the README.md, that is

```
ts-node src/index.ts -i Sherlock\ Holmes\ Selected\ Stories\ / -r -e -s src/styles/retro.css
```

but to my surprise, my environment cannot find the `ts-node` command. I made sure to install TypeScript globally on my environment, so I do not think my issue is regarding TypeScript missing (`npm run build` does run without issue).

**Comment by DukeManh** [comment]
Thanks for the report. I have updated the `readme`. 
You will need to install `ts-node` globally first to execute the program

**Comment by JerryHue** [comment]
Thank you for the clarification! I installed `ts-node` and it runs now.
