### ISSUE TITLE
Test parsing a single text file

### ISSUE THREAD

**Issue by Andrewnt219** [DukeManh/OSD_SSG#16]
## Description

Looking through your e2e tests, there're missing cases for passing a file as an input and use `-r` on a single text file. 

```bash
# file as input
npx ts-node src/index.ts -i text.txt

# -r on a file
npx ts-node src/index.ts -r -i text.txt
```

Definitely worth testing, my program used to crash because of this.

**Comment by DukeManh** [comment]
Thanks, @Andrewnt219. That's an interesting test case.
Do you mind creating a PR for it?
