### ISSUE TITLE
Unclear error message when entering nonexistent file name

### ISSUE THREAD

**Issue by JerryHue** [DukeManh/OSD_SSG#2]
When I run the program with a filename referencing a file that does not exist (let's suppose `hello.txt`), an error will say

> 'hello.txt' is either a file or directory

This is unclear since it does not actually report the actual issue, that being that the file does not exist.

**Comment by JerryHue** [comment]
I would recommend a message that shortly says: `The file 'hello.txt' cannot be found or is missing.`

**Comment by DukeManh** [comment]
Thanks for the recommendation.
I'll do `someFile: No such file or directory`. What do you think?
It's similar to the error of the `ls` command.

**Comment by JerryHue** [comment]
I think it's clear and concise, perfect for a cli tool.
