### ISSUE TITLE
Consider using async fs calls

### ISSUE THREAD

**Issue by humphd** [DukeManh/OSD_SSG#7]
Currently the code is using sync `fs` calls to do all filesystem activity.  This works, but isn't optimal, since it blocks the main thread, and means that the program is going to be unresponsive when processing large amounts of data.

I would suggest you consider using the async versions of `fs` calls, and potentially the `Promise` based versions, so you can keep your style of synchronous coding, but benefit from node's ability to schedule async tasks.

**Comment by DukeManh** [comment]
@humphd, I created a [pull request](https://github.com/DukeManh/OSD_SSG/pull/12) for this issue, would you mind having a look at it? I'd love to learn how it should be done.

**Comment by DukeManh** [comment]
close via https://github.com/DukeManh/OSD_SSG/commit/c0cb195868f08da22257fe9ed1544f7de9921b5a
